name: detect-env
description: Sets node version from nvmrc file.
runs:
  using: "composite"
  steps:
    - name: Determine Node Version
      run: echo NODE_VERSION=$(cat .nvmrc | tr -d '\n') >> $GITHUB_ENV
      shell: bash
