name: Tophat Eslint Config CI

on:
    push:
        tags: 
            - 'v.*'
        branches:
            - '*'
    pull_request:


jobs:
    test_and_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: install
              run: yarn
            - name: lint
              run: yarn lint
            - name: test
              run: yarn test
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: install
              run: yarn
            - name: get tag
              id: get_tag
              run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
            - name: deploy
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run:
                  yarn publish --access public --tag latest --new-version ${{steps.get_tag.outputs.tag}}
